### ISSUE TITLE
new version doesnt work even more than the old one

### ISSUE THREAD

**Issue by yanyannnnyan** [milkteamc/AutoTreeChop#10]
no viplimit  doesnt work on both, on the newest one seems to break the plugin even more than without it
![IMG_2903](https://github.com/user-attachments/assets/b18f42f6-bf5e-4970-a277-11fe2882db47)
![IMG_2901](https://github.com/user-attachments/assets/86816aa3-b521-43c6-afde-5c7db1098576)
 i dont really have any errorcode to show bc theres none

**Comment by MagicTeaMC** [comment]
it should fixed in 1.5.2
