### ISSUE TITLE
config doesnt rlly work

### ISSUE THREAD

**Issue by yanyannnnyan** [milkteamc/AutoTreeChop#9]
i have set vip for everyone but it seems like the limit still applies, even if turned off the said limit so i had to set the limit to be 5 with a lot of zeros

**Comment by yanyannnnyan** [comment]
also it doesnt seem like it even sees the players as having vip at all, im using lucky perms geiser, spigot 1.21

**Comment by yanyannnnyan** [comment]
[New Text Document.txt](https://github.com/user-attachments/files/16542054/New.Text.Document.txt)
this is the server registering the change(thats when i added the permission to myself not just everyone to see if that would work)
so im assuming this is an issue of the perm itself?

**Comment by MagicTeaMC** [comment]
1.5.1 may fix your issue, thanks for your report :)
